#!/usr/bin/env bash
# generate-secrets.sh - bootstrap a Whereas .env file with cryptographically
# random secrets.
#
# Run once when first setting up a deployment. Will refuse to overwrite an
# existing .env. If you need to rotate, do it through the rotation runbook
# (docs/operations/secret-rotation.md), not by re-running this.
#
# All values are generated locally with openssl. Nothing leaves your machine.

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env ]]; then
    echo "ERROR: .env already exists. Refusing to overwrite." >&2
    echo "       To rotate secrets, see docs/operations/secret-rotation.md" >&2
    exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "ERROR: openssl is required but not installed." >&2
    exit 1
fi

gen_hex_32() { openssl rand -hex 32; }
gen_hex_64() { openssl rand -hex 64; }
gen_password() { openssl rand -base64 32 | tr -d '/+=' | head -c 32; }

cat > .env <<EOF
# Generated by scripts/generate-secrets.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Do NOT commit this file to source control.
# Do NOT share these values. They are the keys to your contracts.

# --- Postgres ---
POSTGRES_USER=whereas
POSTGRES_PASSWORD=$(gen_password)

# --- MinIO ---
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$(gen_password)

# --- Whereas backend ---
SECRET_KEY=$(gen_hex_32)
WHEREAS_INSTANCE_KEY=$(gen_hex_32)

# --- LLM provider ---
# Default: local Ollama. Document content never leaves your network.
# To use a remote provider, change LITELLM_PROVIDER and add the API key.
# WARNING: any non-Ollama provider sends document content to a third party.
LITELLM_PROVIDER=ollama
EMBEDDING_MODEL=bge-m3
EXTRACTION_MODEL=llama3.1:70b

# --- Pre-LLM hook ---
# Default: identity (no transformation).
# Set to "block_remote" to refuse all non-local LLM calls regardless of provider config.
# Set to "module.path:callable" to load a custom hook (e.g., a Sonomos integration).
WHEREAS_PRE_LLM_HOOK=identity

# --- DocuSeal integration ---
DOCUSEAL_AUTH_BRIDGE_SECRET=$(gen_hex_32)
DOCUSEAL_SECRET_KEY_BASE=$(gen_hex_64)

# --- Environment ---
ENVIRONMENT=production
LOG_LEVEL=INFO
EOF

chmod 600 .env

cat <<EOF
.env created with fresh random secrets.

Important next steps:
  1. Back up the WHEREAS_INSTANCE_KEY value somewhere safe (a password manager,
     a hardware token, an encrypted file). If you lose it, every encrypted
     document becomes unrecoverable.
  2. Review the LLM provider settings. Default is local Ollama (private).
  3. Run: docker compose up -d
EOF
